### ISSUE TITLE
Support for CommonJs/es2015

### ISSUE THREAD

**Issue by JustinLivi** [millennialmedia/jquery.hx#14]
This may be possible and I'm just doing it wrong, but currently when I try to load jquery.hx as a CommonJs module I hit errors.

I'm running tests in Karma using Babel and Browserify. Both jquery and hx are included as bower components. Jquery loads fine, but importing hx throws the error `Uncaught TypeError: Cannot use 'in' operator to search for 'Float32Array' in undefined` in browserify. I realize that jquery and its plugins were not originally intended to be used in this way.

My import statements look like this:

```javascript
import $ from '../bower_components/jquery/dist/jquery';
import hx from '../bower_components/jquery.hx/dist/hx';
```

**Comment by JustinLivi** [comment]
Something like this: http://blog.npmjs.org/post/112712169830/making-your-jquery-plugin-work-better-with-npm

**Comment by elnarddogg** [comment]
@JustinLivi this is a bug in the version of bezier-easing included in the build:
```javascript
var global = this;
// ...
var float32ArraySupported = 'Float32Array' in global;
```
The context of an anonymous wrapper ends up being `undefined` within a browserify module. I'll update and republish.

**Comment by elnarddogg** [comment]
All set - you'll probably need to use something like [browserify-shim](https://github.com/thlorenz/browserify-shim) since babelify moves requires to the top of the module.

**Comment by JustinLivi** [comment]
Nice, thanks!
